### ISSUE TITLE
Simple cookie clicker not working properly

### ISSUE THREAD

**Issue by LikeItsLikely** [Maingron/MainOS#1]
![Desktop Screenshot 2020 09 30 - 19 46 30 15](https://user-images.githubusercontent.com/72159881/94723146-9662e100-0358-11eb-8102-4786a97a6066.png)

everything else works fine, you can still click the cookies but there is no cookie

**Comment by Maingron** [comment]
@LikeItsLikely thank you. The cookie will be back with version 170.
As you may know though, the Cookie Law is evil and makes publishing cookies difficult :x

**Comment by Maingron** [comment]
Fixed. Will be published with Version 170.
