### ISSUE TITLE
CLI or GUI first? / Base MainOS off a CLI or do GUI only and add CLI stuff later?

### ISSUE THREAD

**Issue by Maingron** [Maingron/MainOS#25]
I think MainOS should be reconsidered. Since MainOS is developing towards a more serious direction now and might potentially be used by some Users eventually, there's a important question that should be answered: 

### Base the GUI off a MainOS CLI or do GUI only and add CLI optionally, later?

While it's possible either way, it should be decided NOW. A CLI is probably hard to write but MainOS is mostly Javascript.
Currently the "Desktop" which is located in index.html has basically Level 0 access. It launches programs and programs can directly talk to it.

If it was based off CLI stuff, it would look more like this:

- Level 0: CLI
- - Level 1: Desktop
- - Level 1: Helper.js
- - - Level 2: Other programs

The CLI is the Root.
The Desktop and Helper.js should then be considered to be some kind of very low level programs.
Other programs would probably still talk to the CLI, like everything would, but the CLI would keep the Programs kind of sandboxed so they can't do everything they want. 

This change would provbably require about 90% of MainOS Core and MainOS API to be re-written, but it would grant way more access for developers or through the CLI and it would be more like an actual OS, probably.

**Comment by StarWolf3000** [comment]
Rebuilding the whole system just to be built up from the ground as CLI would cause more problems now. Instead, I suggest to continue building the GUI version, and adding CLI as additional system module under the GUI.

**Comment by Maingron** [comment]
For now we'll stick with GUI-first. In the current state, it's not worth switching to CLI-first.
