### ISSUE TITLE
App Idea: Browser

### ISSUE THREAD

**Issue by Maingron** [Maingron/MainOS#58]
As a user on itch.io wrote, A webbrowser would be a nice feature.
![grafik](https://user-images.githubusercontent.com/47825439/191239139-e325743d-1974-49da-a56c-5ef8e4038059.png)

**Comment by Maingron** [comment]
Done. See ab3f087ee5dc4318874453fbf8a766f73b17b0f9

**Comment by bogi3bogi** [comment]
Hello there! That was me a year ago and it's nice to see a web browser there!
